// Generated by scripts/sw.mjs. Cache-first service worker so Apex Ring works offline once installed.
const CACHE = "apex-ring-acde81e90a";
const FILES = ["./","./assets/tex/asphalt.jpg","./assets/tex/asphalt_n.jpg","./assets/tex/concrete.jpg","./assets/tex/darkrock.jpg","./assets/tex/darkrock_n.jpg","./assets/tex/drygrass.jpg","./assets/tex/grass.jpg","./assets/tex/grass_n.jpg","./assets/tex/gravel.jpg","./assets/tex/rock.jpg","./assets/tex/rock_n.jpg","./assets/tex/sand.jpg","./assets/tex/snow.jpg","./icons/icon-192.png","./icons/icon-512.png","./icons/icon.svg","./index.html","./manifest.webmanifest","./src/ai.js","./src/assist.js","./src/audio.js","./src/camera.js","./src/career.js","./src/carmodel.js","./src/cars.js","./src/economy.js","./src/effects.js","./src/env.js","./src/ghost.js","./src/ghostcode.js","./src/input.js","./src/main.js","./src/medals.js","./src/minimap.js","./src/music.js","./src/photo.js","./src/race.js","./src/rng.js","./src/save.js","./src/scene.js","./src/scenery.js","./src/showroom.js","./src/terrain.js","./src/textures.js","./src/tilt.js","./src/track.js","./src/trackmesh.js","./src/tracks.js","./src/trophies.js","./src/vehicle.js","./src/version.js","./styles.css","./vendor/three/addons/environments/RoomEnvironment.js","./vendor/three/addons/postprocessing/EffectComposer.js","./vendor/three/addons/postprocessing/MaskPass.js","./vendor/three/addons/postprocessing/OutputPass.js","./vendor/three/addons/postprocessing/Pass.js","./vendor/three/addons/postprocessing/RenderPass.js","./vendor/three/addons/postprocessing/ShaderPass.js","./vendor/three/addons/postprocessing/UnrealBloomPass.js","./vendor/three/addons/shaders/CopyShader.js","./vendor/three/addons/shaders/LuminosityHighPassShader.js","./vendor/three/addons/shaders/OutputShader.js","./vendor/three/addons/utils/BufferGeometryUtils.js","./vendor/three/three.core.js","./vendor/three/three.module.js"];

// A new version installs in the background and waits; the page offers "Update ready" or applies it on next launch.
self.addEventListener("install", (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES))); });
self.addEventListener("message", (e) => { if (e.data === "skipWaiting") self.skipWaiting(); });
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request)));
});
