// Generated by scripts/sw.mjs. Cache-first service worker so Apex Ring works offline once installed.
const CACHE = "apex-ring-ab516b74b3";
const FILES = ["./","./icons/icon-192.png","./icons/icon-512.png","./icons/icon.svg","./index.html","./manifest.webmanifest","./src/ai.js","./src/audio.js","./src/camera.js","./src/career.js","./src/carmodel.js","./src/cars.js","./src/economy.js","./src/effects.js","./src/env.js","./src/input.js","./src/main.js","./src/minimap.js","./src/rng.js","./src/save.js","./src/scene.js","./src/scenery.js","./src/showroom.js","./src/textures.js","./src/track.js","./src/trackmesh.js","./src/tracks.js","./src/vehicle.js","./styles.css","./vendor/three/addons/environments/RoomEnvironment.js","./vendor/three/addons/postprocessing/EffectComposer.js","./vendor/three/addons/postprocessing/MaskPass.js","./vendor/three/addons/postprocessing/OutputPass.js","./vendor/three/addons/postprocessing/Pass.js","./vendor/three/addons/postprocessing/RenderPass.js","./vendor/three/addons/postprocessing/ShaderPass.js","./vendor/three/addons/postprocessing/UnrealBloomPass.js","./vendor/three/addons/shaders/CopyShader.js","./vendor/three/addons/shaders/LuminosityHighPassShader.js","./vendor/three/addons/shaders/OutputShader.js","./vendor/three/addons/utils/BufferGeometryUtils.js","./vendor/three/three.core.js","./vendor/three/three.module.js"];

self.addEventListener("install", (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request)));
});
