// Writes sw.js with the list of files to cache for offline play, versioned by a hash of their contents.
// Run after changing any shipped file: npm run sw  (the tests check the list is complete)
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";

const walk = (d) => readdirSync(d).flatMap((f) => { const p = join(d, f); return statSync(p).isDirectory() ? walk(p) : [p]; });
export function shippedFiles() {
  return ["index.html", "styles.css", "manifest.webmanifest", ...walk("src"), ...walk("vendor").filter((f) => f.endsWith(".js")), ...walk("icons")].sort();
}
const files = shippedFiles();
const hash = createHash("sha1"); for (const f of files) hash.update(f).update(readFileSync(f));
const version = hash.digest("hex").slice(0, 10);
const sw = `// Generated by scripts/sw.mjs. Cache-first service worker so Apex Ring works offline once installed.
const CACHE = "apex-ring-${version}";
const FILES = ${JSON.stringify(["./", ...files.map((f) => "./" + f)], null, 0)};

self.addEventListener("install", (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener("activate", (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || new URL(e.request.url).origin !== location.origin) return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request)));
});
`;
if (process.argv[1].endsWith("sw.mjs")) { writeFileSync("sw.js", sw); console.log("sw.js written,", files.length, "files, version", version); }
