// Writes src/version.js with the package version and the date + short hash of the current commit.
// CI runs this just before deploying, so the shipped game shows exactly what's live. The copy in git says "dev".
import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";

const { version } = JSON.parse(readFileSync("package.json", "utf8"));
let build = "dev";
try { build = execSync("git log -1 --format=%cs·%h", { encoding: "utf8" }).trim(); } catch { /* not a git checkout */ }
writeFileSync("src/version.js", `// Generated by scripts/version.mjs at deploy time.\nexport const VERSION = "${version}";\nexport const BUILD = "${build}";\n`);
console.log("version", version, build);
